---
- name: Provision the development environment
  hosts: dev_servers
  become: yes
  vars_files:
    - group_vars/vars.yml
    - group_vars/vault.yml

  roles:
    - security
    - nginx
    - code-server
    - customization
